covid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView # NOTE AGREGADOS


from servicios.views import *
from servicios.views_CBV import *


urlpatterns = [
    path('admin/', admin.site.urls),

    #path('',TemplateView.as_view(template_name='index_basico.html'),name="home"),
    path('',TemplateView.as_view(template_name='index.html'),name="home"),

    # FBV
    #Servicio
    path('servicios/list',servicios_list,name="servicios_list"),
    path('servicios/<int:id>/moviles',servicios_moviles_list,name="servicios_moviles_list"),
    # ABM 
    path('servicios/nuevo',servicio_abm_nuevo,name="servicios_nuevo"),
    path('servicios/editar/<int:pk>',servicio_abm_editar,name="servicios_editar"),
    path('servicios/borrar/<int:pk>',servicio_abm_borrar,name="servicios_borrar"),

    # CBV
    #Servicio
    path('cbv_servicios/c/list',servicios_list_c.as_view(),name="servicios_list_c"),
    path('cbv_servicios/<int:pk>/moviles',servicios_moviles_list_c.as_view(),name="servicios_moviles_list_c"),
    # ABM 
    path('cbv_servicios/nuevo',servicio_abm_nuevo_c.as_view(),name="servicios_nuevo_c"),
    path('cbv_servicios/editar/<int:pk>',servicio_abm_editar_c.as_view(),name="servicios_editar_c"),
    path('cbv_servicios/borrar/<int:pk>',servicio_abm_borrar_c.as_view(),name="servicios_borrar_c"),
    # Registo 
    path('',include('registros.urls'))
]

moviles/models.py
from django.db import models


# NOTE Definición de Tablas DB => Clases de Django
class Movil(models.Model):
    """
        Model definition del vehículo utilizado.

    """

    # NOTE Definicion de Campos DB => propiedades de la clase.
    # ID no hace falta definirlo
    patente = models.CharField(max_length=10, unique=True)
    servicio = models.ForeignKey("servicios.Servicio", verbose_name="Servicio", on_delete=models.CASCADE)
    observaciones = models.TextField(blank=True, null=True)
    habilitado = models.BooleanField(default=True)
    
    class Meta:
        """Meta definition for servicio."""

        verbose_name = 'Movil'
        verbose_name_plural = 'Moviles'

    def __str__(self):
        """Unicode representation of servicio."""
        #return f'{self.patente} - [{self.servicio.nro_telefono}]'
        return f'{self.patente} - [{self.servicio.nro_telefono}]'

servicios/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

# NOTE Definición de Tablas DB => Clases de Django
class Servicio(models.Model):
    """
        Model definition for servicio.
        107: SAME
        103: Defensa Civil
    """

    # NOTE Definicion de Campos DB => propiedades de la clase.
    # ID no hace falta definirlo
    nombre = models.CharField(max_length=50)
    nro_telefono = models.CharField(max_length=20)
    descripcion = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    version = models.IntegerField(default=0, editable=False)

    class Meta:
        """Meta definition for servicio."""

        verbose_name = 'servicio'
        verbose_name_plural = 'servicios'

    def get_absolute_url(self):
    #    return f"/cbv_servicios/{self.pk}/moviles"
        return reverse('servicios_moviles_list_c', kwargs={'pk': self.pk, })

    def __str__(self):
        """Unicode representation of servicio."""
        return self.nro_telefono

servicios/forms.py
from django import forms

from .models import Servicio

class ABMServicioForm(forms.ModelForm):

    class Meta:
        model = Servicio
        fields = '__all__'

    def validate(self, value):
        super().validate(value)

servicios/views.py
from django.shortcuts import render
from django.views.generic import ListView, FormView
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt

from servicios.models import Servicio
from servicios.forms import ABMServicioForm

# NOTE Vistas de Funciones

@csrf_exempt
def servicios_list(request):
    servicio = Servicio.objects.all()
    return render(request, 'servicios/list_fbv.html', {'s': servicio})

@csrf_exempt
def servicios_moviles_list(request, id):
    servicio = Servicio.objects.get(pk=id)
    return render(request, 'servicios/list_moviles_fbv.html', {'s': servicio})

@csrf_exempt
def servicio_abm_nuevo(request):
    if request.method == "POST":
        form = ABMServicioForm(request.POST)
        if form.is_valid():
            servicio = form.save(commit=False)
            servicio.save()
            # return redirect('servicio_detalle', id=servicio.pk
            return redirect('servicios_list')
    else:
        form = ABMServicioForm()
    return render(request, 'servicios/formulario.html', {'form': form})

@csrf_exempt
def servicio_abm_editar(request, pk):
    servicio = get_object_or_404(Servicio, pk=pk)
    if request.method == "POST":
        form = ABMServicioForm(request.POST, instance=servicio)
        if form.is_valid():
            svr = form.save(commit=False)
            svr.version += 1 
            svr.save()
            return redirect('servicios_list')
    else:
        form = ABMServicioForm(instance=servicio)
    return render(request, 'servicios/formulario.html', {'form': form})

@csrf_exempt
def servicio_abm_borrar(request, pk):
    servicio = get_object_or_404(Servicio, pk=pk)
    servicio.delete()
    return redirect('servicios_list')

servicios/templates/servicios/cbv_list.html
{% extends 'base.html' %}

{% block contenido %}
    <h1>Listado de Servicios</h1>
    {% comment %} <a href="{% url 'alumnos_new' %}"><button type="button" class="btn btn-primary">Nuevo</button></a> {% endcomment %}
    <br>
    <hr>
    <ul>
    {% comment %} {% for svr in object_list %} {% endcomment %}
    {% for svr in s %}
        <li>
            {{ svr.nro_telefono }} => {{ svr.nombre }}

            <a href="{% url 'servicios_moviles_list' id=svr.pk %}"><button type="button" class="btn btn-outline-primary btn-sm"">Moviles</button></a>
            <a href="{% url 'servicios_editar' pk=svr.pk %}"><button type="button" class="btn btn-outline-success btn-sm"">editar</button></a>
            <a href="{% url 'servicios_borrar' pk=svr.pk %}"><button type="button" class="btn btn-outline-danger btn-sm">borrar</button></a> 
        </li>
    {% endfor %}
    </ul>
{% endblock %}

servicios/templates/servicios/formulario.html
{% extends 'base.html' %}

{% block contenido %}
    <h2>Edicion de Servicio</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Grabar</button>
    </form>
{% endblock %}

servicios/templates/servicios/list_fbv.html
{% extends 'base.html' %}

{% block contenido %}
    <h1>Listado de Servicios FBV</h1>
    {% comment %} <a href="{% url 'alumnos_new' %}"><button type="button" class="btn btn-primary">Nuevo</button></a> {% endcomment %}
    <br>
    <hr>
    <ul>
    {% for svr in s %}
        <li>
            {{ svr.nro_telefono }} => {{ svr.nombre }}

            <a href="{% url 'servicios_moviles_list' id=svr.pk %}"><button type="button" class="btn btn-outline-primary btn-sm"">Moviles</button></a>
            <a href="{% url 'servicios_editar' pk=svr.pk %}"><button type="button" class="btn btn-outline-success btn-sm"">editar</button></a>
            <a href="{% url 'servicios_borrar' pk=svr.pk %}"><button type="button" class="btn btn-outline-danger btn-sm">borrar</button></a> 
        </li>
    {% endfor %}
    </ul>
{% endblock %}

servicios/templates/servicios/list_moviles_fbv.html
{% extends 'base.html' %}

{% block contenido %}
    <h1>Listado de Moviles por Servicio FBV</h1>
    {% comment %} <a href="{% url 'alumnos_new' %}"><button type="button" class="btn btn-primary">Nuevo</button></a> {% endcomment %}
    <br>
    <hr>
    <ul>
        <h2>{{ s.nro_telefono }} => {{ s.nombre }}</h2>
        <hr>
 
    {% for m in s.movil_set.all %}
        <li>
           {{m.patente}}
{% comment %} 
            <a href="{% url 'alumnos_detail' pk=alumno.pk %}"><button type="button" class="btn btn-outline-primary btn-sm"">ver</button></a>
            <a href="{% url 'alumnos_edit' pk=alumno.pk %}"><button type="button" class="btn btn-outline-success btn-sm"">editar</button></a>
            <a href="{% url 'alumnos_remove' pk=alumno.pk %}"><button type="button" class="btn btn-outline-danger btn-sm">borrar</button></a> {% endcomment %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

servicios/templates/servicios/servicio_confirm_delete_bck.html
{% extends 'base.html' %}

{% block contenido %}
    <h1>Alta de Servicio CBV</h1>
    <br>
    <hr>
    <form action="" method="post">{% csrf_token %}
        <p>¿Estás seguro de que quieres borrar "{{ object }}"?</p>
        <input type="submit" value="Sí, borrar la página" />
    </form>
{% endblock %}

servicios/templates/servicios/servicio_detail.html
{% extends 'base.html' %}

{% block contenido %}
    <h1>Listado de Moviles por Servicio CBV</h1>
    <br>
    <hr>
    <ul>
        <h2>{{ object.nro_telefono }} => {{ object.nombre }}</h2>
        <hr>
 
    {% for m in object.movil_set.all %}
        <li>
           {{m.patente}}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

servicios/templates/servicios/servicio_form.html
{% extends 'base.html' %}

{% block contenido %}
    <h1>Alta de Servicio CBV</h1>
    <br>
    <hr>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {% comment %} {{ form.as_table }} {% endcomment %}
            {{ form.as_p }}
        </table>
        <br>
        <input type="submit" value="Grabar" />
    </form>
    
{% endblock %}

servicios/templates/servicios/servicio_list-1.html
{% extends 'base.html' %}

{% block contenido %}
    <h1>Listado de Servicios CBV</h1>
    {% comment %} <a href="{% url 'alumnos_new' %}"><button type="button" class="btn btn-primary">Nuevo</button></a> {% endcomment %}
    <br>
    <hr>
    <ul>
    {% for svr in object_list %}
    {% comment %} {% for svr in s %} {% endcomment %}
        <li>
            {{ svr.nro_telefono }} => {{ svr.nombre }}

            <a href="{% url 'servicios_moviles_list_c' pk=svr.pk %}"><button type="button" class="btn btn-outline-primary btn-sm">Moviles</button></a>
            <a href="{% url 'servicios_editar_c' pk=svr.pk %}"><button type="button" class="btn btn-outline-success btn-sm">editar</button></a>
            <a href="{% url 'servicios_borrar_c' pk=svr.pk %}"><button type="button" class="btn btn-outline-danger btn-sm">borrar</button></a> 
        </li>
    {% endfor %}
    </ul>
{% endblock %}

servicios/templates/servicios/servicio_list.html
{% extends 'base.html' %}

{% block contenido %}
    <h1>Listado de Servicios CBV</h1>
    {% comment %} <a href="{% url 'alumnos_new' %}"><button type="button" class="btn btn-primary">Nuevo</button></a> {% endcomment %}
    <br>
    <hr>
    <ul>
    {% for svr in object_list %}
    {% comment %} {% for svr in s %} {% endcomment %}
        <li>
            {{ svr.nro_telefono }} => {{ svr.nombre }}

            <a href="{% url 'servicios_moviles_list_c' pk=svr.pk %}"><button type="button" class="btn btn-outline-primary btn-sm">Moviles</button></a>
            <a href="{% url 'servicios_editar_c' pk=svr.pk %}"><button type="button" class="btn btn-outline-success btn-sm">editar</button></a>
            <a href="{% url 'servicios_borrar_c' pk=svr.pk %}"><button type="button" class="btn btn-outline-danger btn-sm">borrar</button></a> 
        </li>
    {% endfor %}
    </ul>
{% endblock %}